projet_ing1/Yakachoisir/intra_asso/intra_asso/urls.py
from django.contrib import admin
from django.urls import path, include
from social_django.urls import urlpatterns as social_django_urls

from intranet import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((social_django_urls, 'social'))),
    path('', include('intranet.urls')),
]

projet_ing1/Yakachoisir/intra_asso/intranet/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.home_view, name='accueil'),
    path('search/', views.result_search_view, name='search'),
    path('association/<slug:slug>/', views.asso_view, name='asso'),
    path('association/', views.list_asso_view, name="l_asso"),
    path('association/<slug:slug>/enacs/export/', views.export_enac_view, name='export_enac'),
    path('association/<slug:slug>/enacs/', views.enacs_view, name='enacs'),
    path('association/<slug:slug>/finances/', views.finances_view, name='finances'),
    path('association/<slug:slug>/members/', views.member_view, name='l_member'),
    path('association/<slug:slug>/members_delete/<int:user_id>/', views.delete_member_view, name='delete_member'),
    path('association/<slug:slug>/apply_to_asso/', views.apply_to_asso_view, name='apply_asso'),
    path('association/<slug:slug>/apply_list/', views.list_apply_view, name='l_list_apply'),
    path('association/<slug:slug>/apply_resolve/<int:apply_id>/<int:accepted>', views.apply_resolve, name='apply_resolve'),
    path('association/<slug:slug>/reserve/', views.get_room_view, name='reserve'),
    path('association/<slug:slug>/get_board/', views.get_board_list, name='get_board'),
    path('creationassociation/', views.crea_asso_view, name="crea_asso"),
    path('respo/', views.respo_view, name='responsable'),
    path('respo/changestatusasso/<int:apply_id>/<int:accepted>/', views.respo_change_status_asso, name='respo_change_status_asso'),
    path('respo/acceptBudget/<int:budget_id>/<int:accepted>/', views.acceptBudget_view, name='acceptBudget'),
    path('respo/open_enac/', views.demande_open_enac, name='open_enac'),
    path('respo/close_enac/', views.demande_close_enac, name='close_enac'),
    path('user/<login>/', views.user_view, name='user'),
    path('user/', views.list_user_view, name='l_user'),
    path('login/', views.login_view, name='login'),
    path('create/', views.create_user_view, name='create_account'),
    path('disconnect/', views.disconnect, name='disconnect'),
    path('list_asso/', views.get_asso_list, name='asso_list'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projet_ing1/Yakachoisir/intra_asso/intranet/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from guardian.shortcuts import assign_perm
from django.core.mail import EmailMessage
from django.utils.deconstruct import deconstructible
import datetime

# Create your models here.

User = get_user_model()

accepted = 'a'
denied = 'd'
waiting = 'w'

Statut = (
    (accepted, "Accepté"),
    (denied, "Refusé"),
    (waiting, "En attente"),
)


class Association(models.Model):
    name = models.CharField(max_length=100, null=False, primary_key=True)
    chemin_statut = models.FileField(upload_to="files/", null=True)
    email = models.CharField(max_length=100, null=False)
    website = models.URLField(null=True, blank=True)
    description = models.TextField(null=False)
    logo = models.ImageField(upload_to="logo/", null=True, default="logo-epita.png")
    motivation_letter = models.BooleanField()
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    nb_event = models.IntegerField(null=False, default=0)

    login_pres = models.ForeignKey(
        User, on_delete=models.PROTECT, null=False, related_name='%(class)s_pres', default=0)

    comm_pres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])
    work_pres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(50)])
    asso_life_pres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])


    login_vice_pres = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, blank=True, related_name='%(class)s_vice_pres')

    comm_vice_pres = models.IntegerField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])
    work_vice_pres = models.IntegerField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(50)])
    asso_life_vice_pres = models.IntegerField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])

    login_tres = models.ForeignKey(
        User, on_delete=models.PROTECT, null=False, related_name='%(class)s_tres', default=0)

    comm_tres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])
    work_tres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(50)])
    asso_life_tres = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])

    login_secr = models.ForeignKey(
        User, on_delete=models.PROTECT, null=False, related_name='%(class)s_secr', default=0)

    comm_secr = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])
    work_secr = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(50)])
    asso_life_secr = models.IntegerField(null=False, default=0, validators=[MinValueValidator(0), MaxValueValidator(25)])

    members = models.ManyToManyField(User, through='IsMemberOfAssociation')

    def get_board(self):
        return {self.login_pres, self.login_tres, self.login_secr, self.login_vice_pres}

    def __str__(self):
        return self.name

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Association.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == "":
            self.slug = self._get_unique_slug()
        if self.login_pres == self.login_tres \
                or self.login_pres == self.login_secr \
                or self.login_secr == self.login_tres:
            raise ValidationError("La dictature n'est pas autorisée!")

        super(Association, self).save(*args, **kwargs)


class Club(Association):
    depend = models.ForeignKey(
        Association,
        on_delete=models.CASCADE,
        related_name='%(class)s_asso'
    )


class DemandeDeBudget(models.Model):
    emis = models.ForeignKey(
        Association, on_delete=models.CASCADE, null=False)
    fichier_presentation_chemin = models.FileField(upload_to='files/', null=False)
    amount = models.IntegerField(null=False, default=1,
                                 validators=[MinValueValidator(1)]
                                 )
    date = models.DateField(auto_now_add=True)
    dateAccepted = models.DateField(null=True)

    statut = models.CharField(
        max_length=1,
        choices=Statut,
        default=waiting,
        null=False,
    )


class DeclarationDepense(models.Model):
    emis = models.ForeignKey(
        Association, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False)
    fichier_just_chemin = models.FileField(upload_to='files/', null=False)
    date = models.DateTimeField(null=False)
    amount = models.IntegerField(null=False, default=1,
                                 validators=[MinValueValidator(1)]
                                 )
    libelle = models.CharField(null=False, max_length=100)


class DemandeCreationAssociation(models.Model):
    nom_asso = models.CharField(max_length=100, null=False)
    createur = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False)
    file = models.FileField(upload_to='files/', null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

    waiting_cia = 'c'
    waiting_responsable = 'r'

    Statut_Demande = (
        (accepted, "Accepté"),
        (waiting_cia, "En attente(CIA)"),
        (waiting_responsable, "En attente(reponsable)"),
        (denied, "Refusé"),
    )

    statut = models.CharField(
        max_length=1,
        choices=Statut_Demande,
        default=waiting_responsable,
        null=False,
    )

    def changeStatus(self, accepted):
        if self.statut == 'r':
            self.statut = 'c' if accepted else 'd'
        else:
            self.statut = 'a' if accepted else 'd'
        self.save()


class Fichier(models.Model):
    nom_fichier = models.CharField(max_length=100, null=False)
    chemin_fichier = models.FileField(max_length=100, null=False)
    contenu_association = models.ForeignKey(
        Association, on_delete=models.CASCADE)
    contenu_demande_association = models.ForeignKey(
        DemandeCreationAssociation, on_delete=models.CASCADE)


class Reunion(models.Model):
    organise = models.ForeignKey(
        Association, on_delete=models.CASCADE, null=False)
    convoque = models.ManyToManyField(User)
    horaire = models.DateTimeField(null=False)
    lieu = models.CharField(max_length=100, null=False)
    public = models.BooleanField()
    ordre_du_jour_chemin = models.CharField(max_length=100, null=False)
    compte_rendu_chemin = models.CharField(max_length=100)


class IsMemberOfAssociation(models.Model):
    asso = models.ForeignKey('Association', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nb_participation = models.IntegerField(null=False, default=0)
    vice_president = 'p'
    vice_secretaire = 's'
    vice_tresorier = 't'
    defa = 'd'

    Poste = (
        (vice_president, 'vice_président'),
        (vice_secretaire, 'vice_secretaire'),
        (vice_tresorier, 'vice_tresorier'),
        (defa, 'defaut'),
    )
    poste = models.CharField(
        max_length=1,
        choices=Poste,
        default=defa,
        null=False,
    )

    class Meta:
        unique_together = ('asso', 'user')
        permissions = (
            ('view_member', "View Member"),
        )


class IsApplyingTo(models.Model):
    asso = models.ForeignKey('Association', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    motivation_letter = models.TextField(max_length=1000, blank=True)

    statut = models.CharField(
        max_length=1,
        choices=Statut,
        default=waiting,
        null=False,
    )

    def apply_perm(self, user):
        assign_perm('change_isapplyingto', user, self)
        assign_perm('delete_isapplyingto', user, self)
        assign_perm('view_apply', user, self)

    class Meta:
        permissions = (
            ('view_apply', "View Application"),
        )


class ProxyUser(User):

    def is_board(self):
        pres = self.username in [asso.login_pres.username for asso in Association.objects.all()]
        tres = self.username in [asso.login_tres.username for asso in Association.objects.all()]
        secr = self.username in [asso.login_secr.username for asso in Association.objects.all()]
        return pres or tres or secr

    class Meta:
        proxy = True


class ResponsableAsso(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ena_open = models.BooleanField(null=False, default=False)

    @staticmethod
    def is_respo(user):
        return ResponsableAsso.objects.all().first().user == user

    @staticmethod
    def is_enac_open():
        return ResponsableAsso.objects.first().ena_open

    @staticmethod
    def open_enac():
        respo = ResponsableAsso.objects.first()
        if (respo.ena_open):
            return "La demande de formulaire de points ENACS est déjà en cours"
        respo.ena_open = True
        respo.save()
        body = (
                    "Bonjour, la répartition des points ENACS est ouverte. Vous pouvez remplir la page correspondante")

        mails = Association.objects.all().values_list('login_pres').values_list('email')
        mails = [i[0] for i in mails]
        print(mails)
        email = EmailMessage("Demande de création d'association", body, to=mails)
        email.send()

    @staticmethod

projet_ing1/Yakachoisir/intra_asso/intranet/forms.py
from django import forms
from django.forms import modelformset_factory
from django.core.validators import FileExtensionValidator
from .models import IsMemberOfAssociation, Association, DemandeDeBudget, User, DeclarationDepense
import datetime


class EnacBoardForm(forms.ModelForm):
    comm_pres = forms.IntegerField(required=False)
    work_pres = forms.IntegerField(required=False)
    asso_life_pres = forms.IntegerField(required=False)
    comm_vice_pres = forms.IntegerField(required=False)
    work_vice_pres = forms.IntegerField(required=False)
    asso_life_vice_pres = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super(EnacBoardForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Association
        fields = ['comm_pres', 'work_pres', 'asso_life_pres',
                  'comm_vice_pres', 'work_vice_pres', 'asso_life_vice_pres',
                  'comm_secr', 'work_secr', 'asso_life_secr',
                  'comm_tres', 'work_tres', 'asso_life_tres', 'nb_event']


class EnacMemberForm(forms.ModelForm):
    nb_participation = forms.IntegerField()

    class Meta:
        model = IsMemberOfAssociation
        fields = ('nb_participation',)

    def __init__(self, *args, **kwargs):
        super(EnacMemberForm, self).__init__(*args, **kwargs)

    def clean_status(self):
        return self.instance.status


enacFormSet = modelformset_factory(IsMemberOfAssociation, form=EnacMemberForm, extra=0)


class CreateUserForm(forms.Form):
    login = forms.CharField(max_length=30)
    firstname = forms.CharField(max_length=50)
    lastname = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())
    pass_confirm = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super(CreateUserForm, self).clean()
        password = cleaned_data.get('password')
        pass_conf = cleaned_data.get('pass_confirm')

        if pass_conf and password:
            if password != pass_conf:
                raise forms.ValidationError(
                    "Les mots de passe sont différents"
                )
        return cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class ApplyForm(forms.Form):
    motivation_letter = forms.CharField(widget=forms.Textarea, label="Motivation", max_length=1000)


class ChangeUserForm(forms.Form):
    firstname = forms.CharField(max_length=50)
    lastname = forms.CharField(max_length=50)
    email = forms.EmailField()


class ChangeAssoForm(forms.Form):
    email = forms.EmailField()
    website = forms.URLField()


class DemandeCreateAssoForm(forms.Form):
    name = forms.CharField(label="Nom de l'association", max_length=100)
    file = forms.FileField(label="Fichier",
                           validators=[FileExtensionValidator(allowed_extensions=["pdf"])])


class MemberEnacsForm(forms.Form):
    username = forms.CharField(label="username", max_length=30)
    enacs = forms.IntegerField(label="Nombre de points ENACS")


class ReunionForm(forms.Form):
    date = forms.SplitDateTimeField(input_date_formats="%d/%m/%Y",
                                    input_time_formats="%H:%M",
                                    widget=forms.SplitDateTimeWidget(
                                        date_format="%d/%m/%Y",
                                        time_format="%H:%M"))
    lieu = forms.CharField()


class DemandeBudgetForm(forms.ModelForm):
    fichier_presentation_chemin = forms.FileField(label="Fichier",
                                                  validators=[FileExtensionValidator(allowed_extensions=["pdf"])])
    amount = forms.IntegerField(label="Montant")
    emis = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Association.objects.all())

    class Meta:
        model = DemandeDeBudget
        fields = ['fichier_presentation_chemin', 'amount', 'emis']


class DeclareSpent(forms.ModelForm):
    emis = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Association.objects.all())
    user = forms.ModelChoiceField(queryset=User.objects.all())
    amount = forms.IntegerField(label="Montant")
    libelle = forms.CharField(label="Motif", max_length=100)
    date = forms.DateField(label="Date", initial=datetime.date.today, widget=forms.SelectDateWidget())
    fichier_just_chemin = forms.FileField(label="Justificatif",
                                          validators=[FileExtensionValidator(allowed_extensions=["pdf"])])

    class Meta:
        model = DeclarationDepense
        fields = ['fichier_just_chemin', 'amount', 'emis', 'user', 'libelle', 'date']

class AcceptBudgetForm(forms.ModelForm):
    dateAccepted = forms.DateField(label="Date de transfert", initial=datetime.date.today, widget=forms.SelectDateWidget())
    amount = forms.IntegerField(label="Montant")
    
    class Meta:
        model = DemandeDeBudget
        fields = ['dateAccepted', 'amount']

projet_ing1/Yakachoisir/intra_asso/intranet/templates/apply_asso.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}


<div class="container body_pres">
    <div class='row'>
        <div class="col-lg-12">
            <h2>Candidature chez {{ asso.name }}</h2>
            <form method="post" action=".">
                {% csrf_token %} {% if asso.motivation_letter %}
                <textarea class="col-lg-8 h-25" name="motivation_letter" maxlength="500" id="id_motivation_letter"></textarea> {% endif %}
                <p></p>
                <input type="submit" value="Candidater" />
            </form>
        </div>
    </div>
</div>

{% endblock %}

projet_ing1/Yakachoisir/intra_asso/intranet/templates/association.html
<DOCTYPE html>
    <html>

    <head>
        <title> EPITA - Intranet Association </title>
        <meta charset="utf-8" />
        <link rel="stylesheet" type="text/css" href="css/main.css">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <script src="js/jquery.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </head>

    <body class="">
        <div class="container banner-top">
            <div class="row">
                <div class="col-2">
                    <img src="img/logo-epita.png" />
                </div>
                <div class="col align-self-end">
                    <p>Intranet Association</p>
                </div>
            </div>
        </div>
        <div class="container d-flex">
            <button type="button" class="btn btn-link ml-auto">(username) Se déconnecter</button>
        </div>

        <div class="container top_navbar">
            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top sticky-top">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="nav navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="accueil.html">Accueil</a>
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="page_membre.html">Mon Profil</a>
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="creation_association.html">Création d'association</a>
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="association.html">Contact</a>
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                </form>
            </nav>
        </div>
        <div class="container body_pres">
            <div class='row'>
                <div class="col-lg-4">
                    <h2 class="name_pres">Nom de l'association</h2>
                    <img src='img/logo-epita.png'>
                    <button type="button" class="btn btn-outline-primary">Tableau de bord Financier</button>
                    <button type="button" class="btn btn-outline-primary">Gérer l'association</button>
                    <button type="button" class="btn btn-outline-primary">Gérer les candidatures</button>
                    <button type="button" class="btn btn-outline-primary">Exporter/Importer des données</button>
                </div>
                <div class="col-lg-8">
                    <form class="form_assoc rounded">
                        <div class="form-group">
                            <label for="email_assoc">Adresse Email</label>
                            <input type="email" class="form-control" id="email_assoc" aria-describedby="emailHelp" placeholder="Email Association">
                        </div>
                        <div class="form-group">
                            <label for="phone_assoc">Numéro de téléphone</label>
                            <input type="tel" class="form-control" id="phone_assoc" placeholder="Numero de Téléphone">
                        </div>
                        <div class="form-group">
                            <label for="url_assoc">Site Web</label>
                            <input type="url" class="form-control" id="url_assoc" placeholder="Site Web">
                        </div>
                        <button type="submit" class="btn btn-primary">Valider</button>
                    </form>
                </div>
            </div>
        </div>
    </body>

    </html>

projet_ing1/Yakachoisir/intra_asso/intranet/templates/create_account.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href={%  static "css/style.css" %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
    <script src={% static "js/jquery.js" %}></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
</head>
<div class="jumbotron vertical-center">
    <div class="container text-center" >
        <form action="{% url "create_account" %}" method="post">
            {%  csrf_token %}
            <label for="id_login">Login:</label>
            <input type="text" name="login" maxlength="30" required id="id_login" class="form-control" placeholder="Login"/>

            <label for="id_firstname">Prénom</label>
            <input type="text" name="firstname" maxlength="50" required id="id_firstname" class="form-control" placeholder="Prénom"/>

            <label for="id_lastname">Nom</label>
            <input type="text" name="lastname" maxlength="50" required id="id_lastname" class="form-control" placeholder="Nom"/>

            <label for="id_password">Mot de passe</label>
            <input type="password" name="password" required id="id_password" class="form-control" placeholder="Mot de passe" />

            <label for="id_pass_confirm">Confirmation du mot de passe</label>
            <input type="password" name="pass_confirm" required id="id_pass_confirm" class="form-control" placeholder="Confirmation du mot de passe"/>

            <label for="id_email">Adresse email</label>
            <input type="email" name="email" required id="id_email" class="form-control" placeholder="Adresse mail" aria-describedby="emailHelp"/>

            <input type="submit" value="Submit"/>
        </form>
    </div>
</div>
</body>
</html>

projet_ing1/Yakachoisir/intra_asso/intranet/templates/reservation.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}
<div class="container body_pres">
    <div class='row'>
        <div class="col-lg-12">
            <h2>Réservation de salle</h2>
        </div>
    </div>
    <div class='row'>
        <div class="col-lg-12">
            <form class="form_assoc rounded" method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" name="date_0" class="form-control" id="id_date_0" placeholder="Date Réservation">
                    <label>Heure</label>
                    <input type="time" name="date_1" class="form-control" id="id_date_1" placeholder="Heure Réservation">
                    <label id="id_lieu">Salles</label>
                    <select for="id_lieu" name="lieu">
                        {% for resource in resources %}
                        <option value="{{resource.0}}">{{resource.1}}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Valider</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

projet_ing1/Yakachoisir/intra_asso/intranet/templates/temp_asso.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}
<div class="container body_pres">
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="top-button-list">
                <!-- User -->
                {% if not isMember and not isBoard %}
                <a href="apply_to_asso" class="btn btn-outline-primary" role="button">Candidater</a>
                {% endif %}
                <!-- Membre all asso -->
                {% if isMember or isBoard or user.is_staff %}
                <a href="get_board" class="btn btn-outline-primary" role="button">Membres du bureau</a>
                <a href="/list_asso" class="btn btn-outline-primary" role="button">Liste des associations</a>
                {% endif %}
                <!-- Membre -->
                {% if isMember or isBoard or user.is_staff %}
                <a href="apply_list" class="btn btn-outline-primary" role="button">Gestion candidatures</a>
                <a href="finances" class="btn btn-outline-primary" role="button">Tableau de bord Financier</a>
                {% endif %}
                <!-- Bureau -->
                {% if isBoard or user.is_staff %}
                <a href="members" class="btn btn-outline-primary" role="button">Gestion membres</a>
                {% endif %}
                <!-- Pres -->
                {% if asso.login_pres == user or user.is_staff %}
                {% if is_enac_open %}
                <a href="enacs" class="btn btn-outline-primary" role="button">Points ENAC</a>
                {% endif %}
                <a href="reserve" class="btn btn-outline-primary" role="button">Réserver une salle</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class='row'>
        <div class="col-lg-4">
            <h2 class="name_pres">{{ asso.name }}</h2>
            <img src={{ asso.logo.url }}>
        </div>
        <div class="col-lg-8">
            <form class="form_assoc rounded" method="post" action="{% url "asso" slug=asso.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email_assoc">Adresse Email</label>
                    <input type="email" name="email" class="form-control" id="id_email" aria-describedby="emailHelp" placeholder="Email Association" value="{{ asso.email }}" {% if asso.login_pres != user and not user.is_staff  %}disabled{% endif %}>
                </div>
                <div class="form-group">
                    <label for="url_assoc">Site Web</label>
                    <input type="url" name="website" class="form-control" id="id_website" placeholder="Site Web" value="{{ asso.website|default_if_none:" " }}" {% if asso.login_pres != user and not user.is_staff %}disabled{% endif %}>
                </div>
                {% if asso.login_pres == user or user.is_staff %}
                <button type="submit" class="btn btn-primary">Valider</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

projet_ing1/Yakachoisir/intra_asso/intranet/templates/temp_user.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}
<div class="container body_pres">
    <div class='row'>
        <div class="col-lg-4 text-center ">
            <h2 class="name_pres">{{ disUser.first_name }} {{ disUser.last_name }}</h2>
            <img src="https://photos.cri.epita.net/thumb/{{ disUser.username }}" class="rounded w-50">
        </div>
        <div class="col-lg-8">
            <form class="form_assoc rounded" action="{% url "user" login=disUser.username %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="lastname_member">Login</label>
                    <input type="text" name="login" maxlength="30" class="form-control" required id="id_login" placeholder="Login" value="{{ disUser.username }}" disabled>
                </div>
                <div class="form-group">
                    <label for="lastname_member">Nom</label>
                    <input type="text" name="lastname" maxlength="50" class="form-control" id="id_lastname" placeholder="Nom" value="{{ disUser.last_name }}" {% if disUser.username != user.username and not user.is_staff %}disabled{% endif %}>
                </div>
                <div class="form-group">
                    <label for="firstname_member">Prénom</label>
                    <input type="text" name="firstname" maxlength="50" class="form-control" id="id_firstname" placeholder="Prénom" value="{{ disUser.first_name }}" {% if disUser.username != user.username and not user.is_staff %}disabled{% endif %}>
                </div>
                <div class="form-group">
                    <label for="email_member">Adresse Email</label>
                    <input type="email" name="email" class="form-control" id="id_email" placeholder="Email" value="{{ disUser.email }}" {% if disUser.username != user.username and not user.is_staff %}disabled{% endif %}>
                </div>
                {% if disUser.username == user.username  or user.is_staff %}
                <button type="submit" class="btn btn-primary">Valider</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}